version: '3'
services:
  server_31:
    container_name: myserver_31
    build: ./server
    ports:
      - '3006:3006'
    environment:
      - MONGO_URI=mongodb://mongo_31:27022/fp
      - AUTH_MONGO_URI=mongodb://mongo_auth_v3:27025/v3
      - PORT=3006
      - JWT_SECRET=jwtSecret
      - CONFIRM_PASSWORD=vrpshop_server_31
      - AUTH_CONNECTION=true
    volumes:
      - ./server/p31upload:/usr/src/app/p31upload
      - ../controllers:/usr/src/app/controllers
      - ../middleware:/usr/src/app/middleware
      - ./server/routes:/usr/src/app/routes
      - ./server/data/backupData:/usr/src/app/data/backupData
      - ./server/data/initData:/usr/src/app/data/initData
      - ./server/data/restoreData:/usr/src/app/data/restoreData
    links:
      - mongo_31
  mongo_31:
    container_name: mymongo_31
    command: mongod --port 27022 --dbpath /data/db --bind_ip mongo_31
    image: mongo
    ports:
      - '27022:27022'
    volumes:
      - ./mongo/mydb:/data/db

networks: 
  default: 
    external: 
      name: external-network-v3